version: '15'

services:
  zeppelin:
    image: zeppelin
    container_name: zeppelin # Change container name if conflicting
    build:
      context: .
    environment:
      # FLINK_HOME: /opt/flink
      SPARK_HOME: /opt/spark
      ZEPPELIN_LOG_DIR: /opt/zeppelin/logs
      ZEPPELIN_NOTEBOOK_DIR: /opt/zeppelin/notebook 
    volumes:
      - ./logs:/logs
      - ./notebook:/opt/zeppelin/notebook       # notebook folder in main project : path in docker
      - ./spark-3.1.2-bin-hadoop3.2:/opt/spark  # spark folder in main project : path in docker
      # - ./flink-1.18.1:/opt/flink               # flink folder in main project : path in docker
      - ./logs:/opt/zeppelin/logs               # flink folder in main project : path in docker
    ports:
      - 9999:9999
    hostname: zeppelin.local # You can change it into "zeppelin.local" and add into /etc/hosts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 10s
      timeout: 5s
      retries: 3
