FROM yodiaditya/zeppelin-tensorflow-tfx

ENV ZEPPELIN_HOME=/opt/zeppelin
ENV ZEPPELIN_NOTEBOOK_DIR /notebooks
ENV ZEPPELIN_INTERPRETER_DEP_MVNREPO https://repo1.maven.org/maven2/
ENV ZEPPELIN_ADDR 0.0.0.0
ENV SPARK_HOME /opt/bitnami/spark
ENV TZ=UTC \
    DEBIAN_FRONTEND=noninteractive

USER root

# Copy pip-cache folder from host to Docker
# Instead of project folder, it using zeppelin folder as parent directory (Docker: context . )
COPY ./pip-cache ${ZEPPELIN_HOME}/pip-cache
RUN chown -R 1000:1000 ${ZEPPELIN_HOME}/pip-cache

USER 1000
